# Week 2
## Data Exploration and Preparation Practical
### Author: Muhammad Iqbal

In [3]:
import warnings 
warnings.filterwarnings('ignore')

In [4]:
# Import the libraries
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("arbuthnot.txt", sep = r"\s+")

df.head()

   year  boys  girls
0  1629  5218   4683
1  1630  4858   4457
2  1631  4422   4102
3  1632  4994   4590
4  1633  5158   4839

In [5]:
# Check the missing values
df.isnull().sum()

year     0
boys     0
girls    0
dtype: int64

In [7]:
# Check the duplicate values
print(df.duplicated().sum())

0

In [8]:
# Minimum and maximum values of the year
print("First year: ", df["year"].min())
print("Last year: ", df["year"].max())

First year:  1629
Last year:  1710

In [9]:
# Total number of rows and columns
df.shape

(82, 3)

In [10]:
# Detailed information of the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    82 non-null     int64
 1   boys    82 non-null     int64
 2   girls   82 non-null     int64
dtypes: int64(3)
memory usage: 2.1 KB

In [11]:
# Basic statistics
df.describe()

              year         boys        girls
count    82.000000    82.000000    82.000000
mean   1669.500000  5907.097561  5534.646341
std      23.815261  1652.753629  1592.137490
min    1629.000000  2890.000000  2722.000000
25%    1649.250000  4759.250000  4457.000000
50%    1669.500000  6073.000000  5718.000000
75%    1689.750000  7576.500000  7150.250000
max    1710.000000  8426.000000  7779.000000

In [12]:
import matplotlib.pyplot as plt

# Calculate boys-to-girls ratio
df["ratio"] = df["boys"]/df["girls"]

df[["year", "ratio"]]

    year     ratio
0   1629  1.114243
1   1630  1.089971
2   1631  1.078011
3   1632  1.088017
4   1633  1.065923
..   ...       ...
77  1706  1.072132
78  1707  1.090022
79  1708  1.080808
80  1709  1.062331
81  1710  1.048299

[82 rows x 2 columns]

()   paranthesis
{}   Curly brackets
[]   Squafre brackets

In [ ]:
# Size of the Figure
plt.figure(figsize = (8, 4))

# plot function
plt.plot( df["year"], df["ratio"], marker = "o", markersize = 3 )

# Reference when the boys and girls birth are equal
plt.axhline(y = 1, linestyle = "--")

plt.title("Boys-to-Girls Ratio in the London from 1629-1710")
plt.xlabel("Year")
plt.ylabel("Boys-to-Girls Ratio")
plt.grid(True)

# Homework
## Plot the ratio of girls over boys

In [14]:
# Average birth for boys and girls

average_boys = df["boys"].mean()
average_girls = df["girls"].mean()

print("Average number of Boys: ", average_boys)
print("Average number of Girls: ", average_girls)

Average number of Boys:  5907.09756097561
Average number of Girls:  5534.6463414634145

# Plot the birth rae of boys and girls from 1629-1710 and comapre the their births graphically.